### ISSUE TITLE
Upgrade to latest  docker gitolite image will fail with `FATAL: fingerprinting failed for 'keydir/jim.mei.pub'`

### ISSUE THREAD

**Issue by heeeello** [miracle2k/dockerfiles#6]
I am using docker gitolite image to serve my gitolite repos and using the following commnd:
`docker run -d -v /home/git/repositories:/home/git/repositories -e GIT_CONFIG_KEYS='.*' -p 2222:22 elsdoerfer/gitolite`

The above command will report  `FATAL: fingerprinting failed for 'keydir/xx.pub`

After some googling, it seems openssh 6.8 is using newer fingerprinting format and gitolite already upgraded accordingly. See [link1](https://github.com/sitaramc/gitolite/commit/ed807a40c6683960e357bc995b3acf721ec088b4) [link2](http://stackoverflow.com/questions/17300709/gitolite-remote-fatal-fingerprinting-failed-for-keydir/29749581#29749581)

Latest docker gitolite image use openssh 7.2, so finger printing is using latest format, but docker gitolite does not using the latest gitolite accordingly. See [Dockerfile](https://github.com/miracle2k/dockerfiles/blob/master/gitolite/Dockerfile#L25)

Could we upgrade gitolite accordingly?
RIght now I  uploaded old image to docker hub: jimme/gitolite:openssh-6-6p1, which is usable with old repositories

**Comment by white-gecko** [comment]
Here is the according CHANGELOG entry of gitolite: https://github.com/sitaramc/gitolite/blob/v3.6.5/CHANGELOG#L3

**Comment by movcale** [comment]
The same issue for me. For new container I`ve got 
FATAL: fingerprinting failed for 'keydir/admin.pub

And nor able to reconfigure it, even via
docker exec -it gitolite bash
su - git
bin/gitolite setup -pk /path_to_key/my_key.pub

**Comment by miracle2k** [comment]
Seems the only thing necessary here was to upgrade the gitolite version referenced in the Dockerfile.
