### ISSUE TITLE
[gitolite] Can't access repositories, when initialized from existing `repositories/`

### ISSUE THREAD

**Issue by white-gecko** [miracle2k/dockerfiles#7]
I've tried to initialize a gitolite container with and existing `repositories/` folder. But when I try to clone a the `gitolite-admin.git` repo (other repos as well) I get asked for the password, while I'd expect it to be using my public key.
In the logs of the docker container it says: `sh: 1: hooks/post-update: not found`

```
[…]
Initializing gitolite without authorizing a key for accessing the admin repo
Initialized empty Git repository in /home/git/repositories/gitolite-admin.git/
sh: 1: hooks/post-update: not found
Executing /usr/sbin/sshd -D
```

(The existing `repositories/` folder should be from a `3.x` installation, the top entry in the `CHANGELOG` of the original installation is `2012-11-14  v3.2`)

**Comment by DanielBaulig** [comment]
I seem to be running into the same problem. I verified that the volume containing the existing repository was properly mounted. I'll dig a little into the shell script to see why it's apparently not finding the existing admin repository.

**Comment by DanielBaulig** [comment]
It looks like running 

    su git -c "bin/gitolite setup --hooks-only"

just before trying to invoke the hook fixes the problem.

**Comment by miracle2k** [comment]
Closing this because of age, and because the repo moved to https://github.com/miracle2k/docker-gitolite. Hopefully fixed by the above merge request as well.

**Comment by white-gecko** [comment]
Thanks for the info. Could you add some README telling that the repo was moved?
