### ISSUE TITLE
[gitolite] perl: warning: Setting locale failed.

### ISSUE THREAD

**Issue by white-gecko** [miracle2k/dockerfiles#8]
The gitolite image doesn't set the language environment correctly for perl:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_CTYPE = "de_DE.utf8",
    LANG = "de_DE.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by zzgab** [comment]
On a Debian-based system, you could try to place your values in `/etc/environment`:

LANGUAGE=de_DE.UTF-8
LANG=de_DE.UTF-8
LC_ALL=de_DE.UTF-8

**Comment by miracle2k** [comment]
Closing this because of age and because the repo moved to https://github.com/miracle2k/docker-gitolite
