### ISSUE TITLE
[gitolite] Feature:  Mapping host user and group

### ISSUE THREAD

**Issue by movcale** [miracle2k/dockerfiles#9]
Hello,
My dockerized redmine has need for read only access to dockerized gitolite repository folder (via shared volumes).
Unfortunately, gitolite container create a repo folder as [uid=103 gid=109] and with access permissions (drwx------). 
Of course, user (uid=103) on the host machine does not match real 'git' user (or user, which run my dockerized redmine container) on the host machine.

It will be great implement functionality like this: [Mapping host user and group](https://github.com/sameersbn/docker-redmine/blob/master/README.md#mapping-host-user-and-group)
### Mapping host user and group

Per default the container is configured to run redmine as user and group `redmine` with `uid` and `gid` `1000`. The host possibly uses this ids for different purposes leading to unfavorable effects. From the host it appears as if the mounted data volumes are owned by the host's user/group `1000`.

Also the container processes seem to be executed as the host's user/group `1000`. The container can be configured to map the `uid` and `gid` of `redmine` user to different ids on host by passing the environment variables `USERMAP_UID` and `USERMAP_GID`. The following command maps the ids to user and group `redmine` on the host.

``` bash
docker run --name=redmine -it --rm [options] \
  --env="USERMAP_UID=500" --env="USERMAP_GID=500" \
  sameersbn/redmine:3.3.0-3
```

**Comment by movcale** [comment]
As a workaround I did following:
Login into gitolite container and change $UMASK to 0027 in .gitolite.rc [as described here](http://gitolite.com/gitolite/rc.html) 
Add group access to repo dir
chmod -R g+rX /home/git/repositories

And add a host machine docker user into host machine group 109, so it can access to shared repository folder

**Comment by miracle2k** [comment]
Closing this because of age, and because the repo moved to https://github.com/miracle2k/docker-gitolite.
